apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.k8s.erdii.net
  annotations:
    package-operator.run/phase: crds
spec:
  group: k8s.erdii.net
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties: {}
  scope: Cluster
  names:
    plural: foos
    singular: foo
    kind: Foo
    shortNames: []
